#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec s6-setuidgid abc \
    rclone serve http \
        --config="$RCLONE_CONFIG_HTTP" \
        --addr="127.0.0.1:${RCLONE_HTTP_PORT}" \
        "$RCLONE_MOUNT_DIR"
