#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PLEX_URL="$PROXY_PLEX_URL" \
RCLONE_URL="$PROXY_RCLONE_URL" \
PLEX_LIBRARY_PATH="$PROXY_PLEX_LIBRARY_PATH" \
exec s6-setuidgid abc \
    plex-proxy
