#!/usr/bin/with-contenv python3

import os
import sys
from tempfile import mkdtemp
from shutil import rmtree, copyfile
from shlex import quote
from time import sleep
from xml.etree import ElementTree as ET

XMLTV_SOURCES = os.environ.get('XMLTV_SOURCES', None)
if not XMLTV_SOURCES:
    print('XMLTV_SOURCES is not set')
    sys.exit(1)
XMLTV_OUTPUT = os.environ.get('XMLTV_OUTPUT', None)
if not XMLTV_OUTPUT:
    print('XMLTV_OUTPUT is not set')
    sys.exit(1)

sources = XMLTV_SOURCES.split(';')
while True:
    tmp_dir = mkdtemp()
    try:
        out_dir = os.path.join(tmp_dir, 'out')
        main_root = None
        for n, source in enumerate(sources):
            # Download remote
            if source.startswith('http'):
                output_name = os.path.join(tmp_dir, f'{n}.xml')
                os.system(f'curl -L {quote(source)} -o {quote(output_name)}')
                source = output_name
            xml_root = ET.parse(source).getroot()
            if main_root:
                for node in xml_root:
                    main_root.append(node)
            else:
                main_root = xml_root
        # Sort elements
        new_root = ET.Element('tv')
        for node in sorted(main_root, key=lambda n: 'c' + n.attrib.get('id', '') if n.tag == 'channel' else 'p' + n.attrib.get('start', '')):
            new_root.append(node)
        with open(XMLTV_OUTPUT, 'w') as f:
            f.write(ET.tostring(new_root, encoding='unicode'))
    finally:
        rmtree(tmp_dir)

    sleep(60 * 60 * 24)
