#!/usr/bin/with-contenv bash

export INCOMING_LIST=/tmp/incoming.txt
export INCOMING_LIST_TMP=$INCOMING_LIST.tmp
export FILEBOT_PROCESSED=/tmp/amc.txt

if [ ! -d "/config/.filebot" ] && [ -f "${FILEBOT_LICENSE}" ]; then
    s6-setuidgid plex filebot --license "${FILEBOT_LICENSE}"
fi

while true; do
    sleep 63s

    find "$INCOMING_DIR" -type f > $INCOMING_LIST_TMP
    touch $INCOMING_LIST
    if ! cmp --silent $INCOMING_LIST $INCOMING_LIST_TMP; then
        mkdir -p "$FILEBOT_TMP_OUTPUT"
        chown -R plex:plex "$FILEBOT_TMP_OUTPUT"
        s6-setuidgid plex filebot -script fn:amc \
            --output "${FILEBOT_TMP_OUTPUT}" \
            --action duplicate \
            -non-strict \
            --conflict auto \
            --def unsorted=y \
            --def movieFormat="{plex}" seriesFormat="{plex}" \
            --def excludeList=$FILEBOT_PROCESSED \
            "$INCOMING_DIR"

        # Filebot's copying strategy makes rclone sad, hence we copy things separately
        s6-setuidgid plex rsync -r "${FILEBOT_TMP_OUTPUT}/" "${RCLONE_MOUNT_TARGET}"
        s6-setuidgid plex rm -rf "${FILEBOT_TMP_OUTPUT}/*"
    fi

    mv $INCOMING_LIST_TMP $INCOMING_LIST
done
