#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umount "${RCLONE_MOUNT_TARGET}"
mkdir -p "${RCLONE_MOUNT_TARGET}"
chown -R plex:plex "${RCLONE_MOUNT_TARGET}"
chown -R plex:plex "${RCLONE_MOUNT_CACHE_DIR}"
exec s6-setuidgid plex \
    rclone mount -v \
        --config="$RCLONE_CONFIG" \
        --read-only \
        --vfs-read-chunk-size 100M \
        --cache-dir "${RCLONE_MOUNT_CACHE_DIR}" \
        --vfs-cache-mode full \
        --vfs-cache-max-age 4h0m0s \
        --vfs-cache-max-size "${RCLONE_CACHE_MAX_SIZE}" \
        --vfs-cache-poll-interval 1h0m0s \
        "${RCLONE_MOUNT_DIR}" \
        "${RCLONE_MOUNT_TARGET}"
