#!/usr/bin/with-contenv bash

umount ${RCLONE_MOUNT_TARGET}
mkdir -p ${RCLONE_MOUNT_TARGET}
chown -R plex:plex ${RCLONE_MOUNT_TARGET}
exec s6-setuidgid plex /opt/rclone/rclone mount -v --bwlimit 3125 --config="$RCLONE_CONFIG" ${RCLONE_MOUNT_DIR} ${RCLONE_MOUNT_TARGET}
