#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

while ! curl --silent --fail https://id.jottacloud.com:443 >/dev/null; do
    echo "Waiting for caddy..."
    sleep 1
done

umount "${RCLONE_MOUNT_TARGET}" || true

if mountpoint -q "${RCLONE_MOUNT_TARGET}"; then
    echo "${RCLONE_MOUNT_TARGET} is still mounted after umount, refusing to clear it"
    exit 1
fi
rm -rf "${RCLONE_MOUNT_TARGET}"
mkdir -p "${RCLONE_MOUNT_TARGET}"
chown abc:abc "${RCLONE_MOUNT_TARGET}"
chown -R abc:abc "${RCLONE_MOUNT_CACHE_DIR}"
exec s6-setuidgid abc \
    rclone mount -v \
        --config="$RCLONE_CONFIG" \
        --vfs-read-chunk-size 100M \
        --vfs-read-chunk-size-limit 1G \
        --vfs-read-ahead 512M \
        --cache-dir "${RCLONE_MOUNT_CACHE_DIR}" \
        --vfs-cache-mode full \
        --vfs-cache-max-age 4h0m0s \
        --vfs-cache-max-size "${RCLONE_CACHE_MAX_SIZE}" \
        --vfs-cache-poll-interval 1h0m0s \
        --vfs-write-back "${RCLONE_WRITE_BACK}" \
        "${RCLONE_MOUNT_DIR}" \
        "${RCLONE_MOUNT_TARGET}"
